### ISSUE TITLE
Custom music discs uncraftable

### ISSUE THREAD

**Issue by Yo-Snowpro** [Plompi/VinURL#16] opened 2024-08-02 23:03 UTC
Custom Music discs are uncraftable in fabric 1.21

**Comment by Plompi** [comment] 2024-08-03 14:14
Yep, you are right. I dont know why but i will look into that

**Comment by Plompi** [comment] 2024-08-03 15:48
the issue is resolved with the newest version 1.1.3 for 1.21

**Closed by Plompi** 2024-08-03 15:48 UTC
Labels: bug

**Comment by Yo-Snowpro** [comment] 2024-08-03 19:43
Thanks!
